services:
  - type: web
    name: dis-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dis/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  
  - type: web
    name: dis-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://disaster-frontend-n1cn.onrender.com,http://localhost:3000,http://localhost:5173